# Generated by Django 4.0.3 on 2022-04-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='avatar',
            name='more_description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
